name: 02hero
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.2.0=py39h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=1.2.3=py39h06a4308_1
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backoff=2.2.1=py39h06a4308_1
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=py39h06a4308_0
  - blas=1.0=mkl
  - blessed=1.20.0=py39h06a4308_0
  - boto3=1.34.82=py39h06a4308_0
  - botocore=1.34.82=py39h06a4308_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py39h06a4308_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.0.5=py39hdb19cb5_0
  - croniter=1.3.7=py39h06a4308_0
  - cryptography=41.0.2=py39h22a60cf_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - daal4py=2023.1.1=py39h79cecc1_0
  - dal=2023.1.1=hdb19cb5_48679
  - dateutils=0.6.12=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deepdiff=7.0.1=py39h2f386ee_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.4.9=h6a678d5_0
  - fastapi=0.103.0=py39h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.3.1=py39h06a4308_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py39h06a4308_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - inquirer=3.1.4=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.25.0=pyh71e2992_0
  - ipython=8.14.0=pyh41d4057_0
  - itsdangerous=2.2.0=py39h06a4308_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.4=py39h06a4308_0
  - jmespath=1.0.1=py39h06a4308_0
  - joblib=1.2.0=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_core=4.12.0=py39hf3d152e_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lightning=2.0.9.post0=py39h06a4308_0
  - lightning-cloud=0.5.57=py39h06a4308_0
  - lightning-utilities=0.9.0=py39h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=2.2.0=py39h06a4308_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib=3.7.1=py39h06a4308_1
  - matplotlib-base=3.7.1=py39h417a72b_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=py39h06a4308_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - mpi=1.0=mpich
  - mpich=4.1.1=hbae89fd_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.4=py39hc78ab66_1
  - numpy=1.25.0=py39h5f9d8c6_0
  - numpy-base=1.25.0=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.14=h5eee18b_0
  - ordered-set=4.1.0=py39h06a4308_0
  - orjson=3.9.15=py39h97a8848_0
  - packaging=23.0=py39h06a4308_0
  - pandas=1.5.3=py39h417a72b_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.2.1=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py39h5eee18b_1
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=py39h06a4308_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.17=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-editor=1.0.4=pyhd3eb1b0_0
  - python-multipart=0.0.6=py39h06a4308_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-lightning=2.0.3=py39h06a4308_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py39h06a4308_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - pyzmq=25.1.0=py39h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readchar=4.0.5=py39h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_0
  - rich=13.7.1=py39h06a4308_0
  - s3transfer=0.10.1=py39h06a4308_0
  - scikit-learn=1.3.0=py39h1128e8f_0
  - scikit-learn-intelex=2023.1.1=py39h06a4308_0
  - scipy=1.10.1=py39hf6e8229_1
  - setuptools=68.0.0=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py39h06a4308_0
  - soupsieve=2.5=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - starlette=0.27.0=py39h06a4308_0
  - starsessions=1.3.0=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py39_cu113
  - torchmetrics=1.4.0.post0=py39h06a4308_0
  - torchvision=0.13.1=py39_cu113
  - tornado=6.3.2=py39h5eee18b_0
  - tqdm=4.66.4=py39h2f386ee_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.11.0=py39h06a4308_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py39h06a4308_0
  - uvicorn=0.20.0=py39h06a4308_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - websocket-client=1.8.0=py39h06a4308_0
  - websockets=10.4=py39h5eee18b_1
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - bio==1.6.2
      - biopython==1.83
      - biothings-client==0.3.1
      - chardet==5.2.0
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gprofiler-official==1.0.0
      - mygene==3.2.2
      - platformdirs==4.2.2
      - protobuf==5.27.2
      - sentry-sdk==2.10.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tabulate==0.9.0
      - wandb==0.17.4
prefix: /home/digivjay/miniconda3/envs/02hero
